version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shopping_list_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopping_list_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: shopping_list_api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: shopping_list_db
      DB_SSLMODE: disable
      PORT: 8080
      GIN_MODE: release
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
